/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ControleRouteImport } from './routes/controle'
import { Route as ConexoesRouteImport } from './routes/conexoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConnectionsDerivCallbackRouteImport } from './routes/api.connections.deriv.callback'

const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleRoute = ControleRouteImport.update({
  id: '/controle',
  path: '/controle',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexoesRoute = ConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsDerivCallbackRoute =
  ApiConnectionsDerivCallbackRouteImport.update({
    id: '/api/connections/deriv/callback',
    path: '/api/connections/deriv/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/controle': typeof ControleRoute
  '/historico': typeof HistoricoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/api/connections/deriv/callback': typeof ApiConnectionsDerivCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/controle': typeof ControleRoute
  '/historico': typeof HistoricoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/api/connections/deriv/callback': typeof ApiConnectionsDerivCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conexoes': typeof ConexoesRoute
  '/controle': typeof ControleRoute
  '/historico': typeof HistoricoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/api/connections/deriv/callback': typeof ApiConnectionsDerivCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conexoes'
    | '/controle'
    | '/historico'
    | '/inteligencia'
    | '/knowledge'
    | '/login'
    | '/mercado'
    | '/api/connections/deriv/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conexoes'
    | '/controle'
    | '/historico'
    | '/inteligencia'
    | '/knowledge'
    | '/login'
    | '/mercado'
    | '/api/connections/deriv/callback'
  id:
    | '__root__'
    | '/'
    | '/conexoes'
    | '/controle'
    | '/historico'
    | '/inteligencia'
    | '/knowledge'
    | '/login'
    | '/mercado'
    | '/api/connections/deriv/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConexoesRoute: typeof ConexoesRoute
  ControleRoute: typeof ControleRoute
  HistoricoRoute: typeof HistoricoRoute
  InteligenciaRoute: typeof InteligenciaRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  ApiConnectionsDerivCallbackRoute: typeof ApiConnectionsDerivCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle': {
      id: '/controle'
      path: '/controle'
      fullPath: '/controle'
      preLoaderRoute: typeof ControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexoes': {
      id: '/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof ConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/deriv/callback': {
      id: '/api/connections/deriv/callback'
      path: '/api/connections/deriv/callback'
      fullPath: '/api/connections/deriv/callback'
      preLoaderRoute: typeof ApiConnectionsDerivCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConexoesRoute: ConexoesRoute,
  ControleRoute: ControleRoute,
  HistoricoRoute: HistoricoRoute,
  InteligenciaRoute: InteligenciaRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  ApiConnectionsDerivCallbackRoute: ApiConnectionsDerivCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
